### PR TITLE
Integrate EPS subsystem and commands via UART

### LINKED ISSUE #12: Integrate EPS functions, when complete
- [x] Add function files
- [x] Plan out where to integrate the functions
- [x] Integrate the functions into the main firmware

### Integration:
* Periodic logging
* Power toggle calls
* Power monitoring of subsystems when active
* Initial state configuration/reset/fail safe
* Initial boom deployments

### PR DESCRIPTION
**Pull request by DeflateAwning**
Fixes #12

### CODE REVIEW

File: firmware/Core/Inc/eps_drivers/eps_debug_tools.h [hunk 1]
```diff
@@ -0,0 +1,11 @@
+
+#ifndef __INCLUDE_GUARD__EPS_DEBUG_TOOLS_H__
+#define __INCLUDE_GUARD__EPS_DEBUG_TOOLS_H__
+
+#include "eps_drivers/eps_types.h"
+
+void EPS_debug_uart_print_system_status(EPS_result_system_status_t* system_status);
```
Comment (JohnathanBurchill) [inline firmware/Core/Inc/eps_drivers/eps_debug_tools.h:7]: How far should upper-case namespace extend? Like EPS_DEBUG_UART_print_system_status(...

File: firmware/Core/Inc/eps_drivers/eps_internal_drivers.h [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+#define EPS_MAX_RESPONSE_POLL_TIME_MS 100
+
+
+// #pragma endregion Constants
+
+
+// #pragma region Function_Prototypes
+
+uint8_t eps_send_cmd_get_response(const uint8_t cmd_buf[], uint8_t cmd_buf_len,
```
Comment (JohnathanBurchill) [inline firmware/Core/Inc/eps_drivers/eps_internal_drivers.h:36]: Namespace EPS

File: firmware/Core/Src/telecommands/eps_telecommands.c [hunk 3]
```diff
@@ -0,0 +1,24 @@
+#include <eps_drivers/eps_commands.h>
+#include <eps_drivers/eps_types.h>
+
+#include <telecommands/eps_telecommands.h>
+
+#include <stdio.h>
+
+/// @brief Triggers the EPS watchdog. No args.
+/// @return 0 on success, 1 on failure.
+uint8_t TCMDEXEC_eps_watchdog(const uint8_t *args_str, TCMD_TelecommandChannel_enum_t tcmd_channel,
```
Comment (JohnathanBurchill) [inline firmware/Core/Src/telecommands/eps_telecommands.c:10]: Suggest TCMDEXEC_EPS_watchdog (namespace case)

File: firmware/Core/Src/telecommands/telecommand_definitions.c [hunk 4]
```diff
@@ -52,7 +54,17 @@ const TCMD_TelecommandDefinition_t TCMD_telecommand_definitions[] = {
         .tcmd_name = "available_telecommands",
         .tcmd_func = TCMDEXEC_available_telecommands,
         .number_of_args = 0,
-    }
+    },
+
+    /* ============================ EPS-Related (eps_telecommands.c/h) ================= */
+    {
+        .tcmd_name = "eps_watchdog",
+        .tcmd_func = TCMDEXEC_eps_watchdog,
```
Comment (JohnathanBurchill) [inline firmware/Core/Src/telecommands/telecommand_definitions.c:62]: Namespace case

File: firmware/Core/Src/uart_handler/uart_handler.c [hunk 5]
```diff
@@ -2,20 +2,32 @@
 #include "debug_tools/debug_uart.h"
 #include "main.h"
 
+// Name the UART interfaces
+UART_HandleTypeDef *UART_telecommand_port_handle = &hlpuart1;
+UART_HandleTypeDef *UART_eps_port_handle = &huart5; // TODO: update this
```
Comment (JohnathanBurchill) [inline firmware/Core/Src/uart_handler/uart_handler.c:7]: Case on namespace?

**Review by JohnathanBurchill — COMMENTED** [review]
Suggest to check nested namespaces in functions / variables, like EPS_debug -> EPS_DEBUG (?) or UART_eps -> UART_EPS (?).

Suggest eps_telecommands.c -> telecommands_eps.c to unify file naming.

Compiles and flashes using my mac. I get this error when running eps_watchdog() telecommand: 

```
UTC=2024-06-13T01:37:45.741502: Received telecommand (len=19): 'CTS1+eps_watchdog()'
======= Telecommand ======
Received telecommand 'eps_watchdog'
OBC->EPS (no tags): 0x1a 0x07 0x06 0x00
OBC->EPS (with tags): 0x3c 0x63 0x6d 0x64 0x3e 0x1a 0x07 0x06 0x00 0x3c 0x2f 0x63 0x6d 0x64 0x3e
OBC -> EPS TIMEOUT ERROR: HAL_GetTick() - UART_eps_last_write_time_ms > EPS_RX_TIMEOUT_MS
EPS->OBC (with tags):
OBC -> EPS ERROUTC=2024-06-13T01:37:45.798406: R: UART_eps_buffer_write_idx == 0
======== Response ========
EPS watchdog trigger failed (err 3)
==========================
```

File: firmware/Core/Inc/eps_drivers/eps_debug_tools.h (hunk 1 above)
Comment (DeflateAwning) [reply firmware/Core/Inc/eps_drivers/eps_debug_tools.h:7]: Just to match one of the namespaces listed in the [/docs/C_Namespaces.md file](https://github.com/CalgaryToSpace/CTS-SAT-1-OBC-Firmware/blob/main/docs/C_Namespaces.md). So in this case, just `EPS_xxxx` is good.

The goal with the namespaces is just to emphasize that every piece of code in repo needs to have a reason to be in the repo, and a reason to be executed/used. Namespaces help avoid accidentally using them between systems that don't make sense (especially in struct/enum typedefs, where there could otherwise be multiple `result_system_status_t` struct definitions).

File: firmware/Core/Src/telecommands/eps_telecommands.c (hunk 3 above)
Comment (DeflateAwning) [reply firmware/Core/Src/telecommands/eps_telecommands.c:10]: I think we'll keep all command names fully lowercase to avoid errors while planning/uplinking telecommands. The `xxx` part in `TCMDEXEC_xxx` should match the telecommand's name string (defined in the telecommand table), and thus remains lowercase. 

Ensuring that the subsystem is explicitly stated at the start of the telecommand name is 100% a requirement though, regardless of capitalization.

Comment (JohnathanBurchill) [reply firmware/Core/Src/telecommands/eps_telecommands.c:10]: Got it. All good re namespaces.

**Comment by JohnathanBurchill** [comment]
I figure that error is telling me that I don't have an EPS system attached to the dev kit :)

**Comment by JohnathanBurchill** [comment]
Error message is clearer:

```
UTC=2024-06-13T12:35:51.012792: Received telecommand (len=19): 'CTS1+eps_watchdog()'
UTC=2024-06-13T12:35:51.068617: ======= Telecommand ======
Received telecommand 'eps_watchdog'
OBC->EPS DATA (no tags): 0x1a 0x07 0x06 0x00
OBC->EPS DATA (with tags): 0x3c 0x63 0x6d 0x64 0x3e 0x1a 0x07 0x06 0x00 0x3c 0x2f 0x63 0x6d 0x64 0x3e
UTC=2024-06-13T12:35:51.125143: EPS->OBC ERROR: timeout before first byte received
======== Response ========
EPS watchdog trigger failed (err 3)
==========================
```

**Comment by DeflateAwning** [comment]
@robotoshi, do you think you could plan to help with this one?

**Comment by robotoshi** [comment]
Yeah I'll take a look

**Comment by DeflateAwning** [comment]
@JohnathanBurchill, if you have any capacity to give this a quick glance, would love any feedback/sanity check you're able to provide this week before we merge it. No worries if you're tight on time though!

**Comment by DeflateAwning** [comment]
Going to merge this now as other projects (e.g., #19) are depending on the UART setup in this PR. Super open to any feedback anyone has if they get a chance to review :)
