### PR TITLE
fix: Invalid error message cast

### LINKED ISSUE #382: Bug: Logs - checkout this line (bad type cast)
In `log/log.c`, check out:

```c
    LOG_message(LOG_SYSTEM_LOG, LOG_SEVERITY_ERROR, LOG_SINK_ALL, "LOG_set_sink_state(): unknown system: %ld", (uint32_t) system);
```

`system` is not right there

Also, should rename all "log system" to "log source" for clarity probably

### PR DESCRIPTION
**Pull request by DeflateAwning**
Fixes #382

### CODE REVIEW

File: firmware/Core/Src/log/log.c [hunk 1]
```diff
@@ -331,7 +331,7 @@ void LOG_set_sink_enabled_state(LOG_sink_enum_t sink, uint8_t state)
     }
 
     // Sink not found
-    LOG_message(LOG_SYSTEM_LOG, LOG_SEVERITY_ERROR, LOG_SINK_ALL, "LOG_set_sink_state(): unknown system: %ld", (uint32_t) system);
+    LOG_message(LOG_SYSTEM_LOG, LOG_SEVERITY_ERROR, LOG_SINK_ALL, "LOG_set_sink_state(): unknown sink: %d", sink);
```
Comment (robotoshi) [inline firmware/Core/Src/log/log.c:334]: Amazing, great catch!

**Review by robotoshi — APPROVED** [review]
Fixes the bug very nicely
